apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip-api
  namespace: monitoring
  labels:
    app: geoip-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: geoip-api

  template:
    metadata:
      labels:
        app: geoip-api

    spec:
      containers:
        - name: geoip-api
          image: ghcr.io/observabilitystack/geoip-api:2026-20
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: PORT
              value: "8080"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

        

---
apiVersion: v1
kind: Service
metadata:
  name: geoip-api
  namespace: monitoring

spec:
  type: ClusterIP

  selector:
    app: geoip-api

  ports:
    - name: http
      port: 80
      targetPort: 8080