apiVersion: apps/v1
kind: Deployment
metadata:
  name: foto-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fotocontainer
  template:
    metadata:
      labels:
        app: fotocontainer
    spec:
      volumes:
        - name: foto-nfs
          persistentVolumeClaim:
            claimName: foto-nfs-pvc
      restartPolicy: Always
      containers:
        - name: foto-app
          image: marcel88/foto_app_pi:v16
          volumeMounts:
            - name: foto-nfs
              mountPath: /nfs/fotoproject
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__SQLConnection
              value: Server=db-0.mariadb-headless-service.mariadb.svc.cluster.local;Port=3306;Database=foto;User=root;Password=example;Allow User Variables=true

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: foto-service
spec:
  type: ClusterIP
  selector:
    app: fotocontainer
  ports:
    - port: 80
      targetPort: 8080


