apiVersion: v1
kind: PersistentVolume
metadata:
  name: foto-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.1
  nfs:
    server: 192.168.2.22
    path: /volume1/fotoproject/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foto-nfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: foto-nfs-pv
  storageClassName: ""
