apiVersion: apps/v1
kind: Deployment
metadata:
  name: foto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foto
  template:
    metadata:
      labels:
        app: foto
    spec:
      volumes:
        - name: foto-nfs
          persistentVolumeClaim:
            claimName: foto-nfs-pvc
      restartPolicy: Always
      containers:
        - name: foto-app
          image: marcel88/foto-main-pi:v22
          volumeMounts:
            - name: foto-nfs
              mountPath: /nfs/fotoproject
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__SQLConnection
              value: Server=db-0.mariadb-headless-service.mariadb.svc.cluster.local;Port=3306;Database=main;User=root;Password=example;Allow User Variables=true
            - name: ComSettings__VideoUrl
              value: http://video-service/
            - name: ComSettings__PhotoContainerUrl
              value: http://foto-container-service/




---
# Service
apiVersion: v1
kind: Service
metadata:
  name: foto-main-service
spec:
  type: ClusterIP
  selector:
    app: foto
  ports:
    - port: 80
      targetPort: 8080


