apiVersion: v1
kind: PersistentVolume
metadata:
  name: foto-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.22
    path: /volume1/microksData/fotoproject
  persistentVolumeReclaimPolicy: Retain
