apiVersion: v1
kind: ConfigMap
data:
 use-forwarded-headers: "true"
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-load-balancer-microk8s-conf","namespace":"ingress"}}
  creationTimestamp: "2025-12-16T12:59:07Z"
  name: nginx-load-balancer-microk8s-conf
  namespace: ingress
  resourceVersion: "5869534"
  uid: 57c06fba-3a86-4b0f-99ed-0acb9c2bd222
